- name: Add suricata ppa repo
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:oisf/suricata-stable"
    state: present

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install suricata
  become: true
  ansible.builtin.apt:
    name: 
      - suricata
      - jq

- name: Force reinstall libhtp2
  become: true
  ansible.builtin.shell:
    cmd: apt install --reinstall libhtp2

- name: Suricata-Update enable sources
  become: true
  ansible.builtin.shell:
    cmd: "suricata-update update-sources && suricata-update enable-source {{ item }}"
    creates: /var/lib/suricata/rules/suricata.rules
  loop: "{{ suricata_update_rules }}"
  notify: Update suricata

- name: Configure surciata
  become: true
  ansible.builtin.template:
    src: "{{ suricata_tpl }}"
    dest: "/etc/suricata/suricata.yaml"
    mode: "0644"
    owner: "root"
    group: "root"
  notify: Restart suricata

- name: Configure surciata-threshold
  become: true
  ansible.builtin.template:
    src: "{{ suricata_threshold_tpl }}"
    dest: "{{ suricata_threshold_file }}"
    mode: "0644"
    owner: "root"
    group: "root"
  notify: Restart suricata

- name: Start and enable service suricata
  become: true
  ansible.builtin.systemd:
    name: suricata
    state: restarted
    enabled: true
