- name: Install suricata
  apt:
    name: suricata
    state: present

- name: Install suricata-update
  apt:
    name: suricata-update
    state: present

- name: Suricata-Update enable sources
  ansible.builtin.shell:
    creates: /var/lib/suricata/rules/suricata.rules
    cmd: "suricata-update update-sources && suricata-update enable-source {{ item }}"
  loop:
    - et/open
    - tgreen/hunting
    - malsilo/win-malware
    - stamus/lateral
  notify:
    - suricata-update

- name: Configure default file
  template:
          src: "{{ suricata_default_tpl }}"
          dest: "/etc/default/suricata"
          mode: "0644"
          owner: "root"
          group: "root"
  notify: restart suricata

- name: Configure surciata
  template:
          src: "{{ suricata_tpl }}"
          dest: "/etc/suricata/suricata.yaml"
          mode: "0644"
          owner: "root"
          group: "root"
  notify: restart suricata

- name: Configure surciata-threshold
  template:
          src: "{{ suricata_threshold_tpl }}"
          dest: "/etc/suricata/threshold.config"
          mode: "0644"
          owner: "root"
          group: "root"
  notify: restart suricata


- name: Start service suricata, if not started
  service:
    name: suricata
    state: started
