
- name: Add suricata ppa repo
  apt_repository:
    filename: suricata_repo
    repo: "ppa:oisf/suricata-stable"
    state: present
    update_cache: true
  when: suricata_use_ppa|bool

- name: Install suricata
  apt:
    name: suricata
    state: present

- name: Add custom rule files
  copy:
    src: "{{ item }}"
    dest: "{{ suricata_rule_path }}/{{ item | basename }}"
    mode: "0644"
    owner: root
    group: root
  loop: "{{ suricata_extra_rule_files }}"
  notify: restart suricata

- name: Configure default file
  template:
          src: "{{ suricata_default_tpl }}"
          dest: "/etc/default/suricata"
          mode: "0644"
          owner: "root"
          group: "root"
  notify: restart suricata

- name: Configure surciata
  template:
          src: "{{ suricata_tpl }}"
          dest: "/etc/suricata/suricata.yaml"
          mode: "0644"
          owner: "root"
          group: "root"
  notify: restart suricata

- name: Start service suricata, if not started
  service:
    name: suricata
    state: started